-- Easter egg: un cupón 10% por dispositivo (solo desde catálogo)
-- Ejecutar en Supabase SQL Editor

CREATE TABLE IF NOT EXISTS easter_claims (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id text NOT NULL,
  coupon_code text NOT NULL,
  created_at timestamptz DEFAULT now(),
  UNIQUE(device_id)
);

CREATE INDEX IF NOT EXISTS easter_claims_device_id_idx ON easter_claims(device_id);

-- RLS: solo el backend (service role) escribe; anon no tiene acceso
ALTER TABLE easter_claims ENABLE ROW LEVEL SECURITY;

-- Sin políticas para anon/authenticated: el API usa service_role y bypasea RLS
COMMENT ON TABLE easter_claims IS 'Un cupón 10% por dispositivo al activar easter egg en el catálogo.';
