-- Historial de movimientos de stock (3.2)
-- Ejecutar en Supabase: SQL Editor → New query → Pegar y Run

CREATE TABLE IF NOT EXISTS stock_movements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  type text NOT NULL CHECK (type IN ('sale', 'purchase', 'adjustment')),
  quantity int NOT NULL,
  reference_type text,
  reference_id bigint,
  notes text,
  created_at timestamptz DEFAULT now(),
  user_id uuid REFERENCES auth.users(id)
);

CREATE INDEX IF NOT EXISTS idx_stock_movements_product_id ON stock_movements(product_id);
CREATE INDEX IF NOT EXISTS idx_stock_movements_created_at ON stock_movements(created_at DESC);

COMMENT ON TABLE stock_movements IS 'Historial de entradas/salidas por producto: sale (venta), purchase (compra), adjustment (ajuste manual). quantity negativo = salida.';
COMMENT ON COLUMN stock_movements.reference_id IS 'Ej: sale_id cuando type=sale';

-- RLS: usuarios autenticados pueden ver e insertar movimientos
ALTER TABLE stock_movements ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated can manage stock_movements"
  ON stock_movements FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);
