-- Descuento por producto (catálogo) y cupones
-- Ejecutar en Supabase SQL Editor

-- 1. Columna de descuento en products (porcentaje 0-100, null = sin descuento)
ALTER TABLE products
ADD COLUMN IF NOT EXISTS discount_percentage integer DEFAULT 0 CHECK (discount_percentage >= 0 AND discount_percentage <= 100);

-- 2. Tabla de cupones (código + porcentaje de descuento sobre el total)
CREATE TABLE IF NOT EXISTS coupons (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL,
  discount_percentage integer NOT NULL CHECK (discount_percentage >= 0 AND discount_percentage <= 100),
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now()
);

-- Un solo cupón por código (sin importar mayúsculas)
CREATE UNIQUE INDEX IF NOT EXISTS coupons_code_upper_key ON coupons (upper(trim(code)));

-- RLS: permitir lectura anónima solo de cupones activos (para validar en catálogo)
ALTER TABLE coupons ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Cupones activos son legibles por anon"
  ON coupons FOR SELECT
  TO anon
  USING (is_active = true);

-- Autenticados (admin) pueden hacer todo sobre cupones
CREATE POLICY "Autenticados gestionan cupones"
  ON coupons FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Comentarios
COMMENT ON COLUMN products.discount_percentage IS 'Porcentaje de descuento en catálogo (0-100). Muestra "En descuento" y precio rebajado.';
COMMENT ON TABLE coupons IS 'Cupones para el catálogo público. code en mayúsculas sin espacios para comparar.';
