-- =============================================================================
-- Stage 6.5 — CRM mínimo de clientes
-- =============================================================================
-- Datos CRM sensibles: tablas sin acceso Data API directo. Toda operación pasa
-- por RPC admin-only con autorización interna y auditoría append-only.

CREATE TABLE public.customer_tags (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL CHECK (char_length(trim(name)) BETWEEN 2 AND 30),
  color text NOT NULL DEFAULT '#ec4899'
    CHECK (color ~ '^#[0-9A-Fa-f]{6}$'),
  created_by uuid NOT NULL REFERENCES auth.users(id),
  updated_by uuid REFERENCES auth.users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX customer_tags_normalized_name_idx
  ON public.customer_tags (lower(trim(name)));

CREATE TABLE public.customer_tag_assignments (
  customer_id integer NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE,
  tag_id bigint NOT NULL REFERENCES public.customer_tags(id) ON DELETE CASCADE,
  assigned_by uuid NOT NULL REFERENCES auth.users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (customer_id, tag_id)
);

CREATE INDEX customer_tag_assignments_tag_idx
  ON public.customer_tag_assignments (tag_id, customer_id);

CREATE TABLE public.customer_notes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id integer NOT NULL REFERENCES public.customers(id) ON DELETE RESTRICT,
  body text NOT NULL CHECK (char_length(trim(body)) BETWEEN 1 AND 1000),
  created_by uuid NOT NULL REFERENCES auth.users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  archived_at timestamptz,
  archived_by uuid REFERENCES auth.users(id),
  CHECK (
    (archived_at IS NULL AND archived_by IS NULL)
    OR (archived_at IS NOT NULL AND archived_by IS NOT NULL)
  )
);

CREATE INDEX customer_notes_customer_created_idx
  ON public.customer_notes (customer_id, created_at DESC);

CREATE TABLE public.customer_consent_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id integer NOT NULL REFERENCES public.customers(id) ON DELETE RESTRICT,
  channel text NOT NULL DEFAULT 'marketing' CHECK (channel = 'marketing'),
  granted boolean NOT NULL,
  source text NOT NULL CHECK (
    source IN ('presencial', 'whatsapp', 'web', 'telefono', 'otro')
  ),
  evidence_note text CHECK (
    evidence_note IS NULL OR char_length(trim(evidence_note)) BETWEEN 1 AND 500
  ),
  recorded_by uuid NOT NULL REFERENCES auth.users(id),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX customer_consent_events_customer_created_idx
  ON public.customer_consent_events (customer_id, created_at DESC, id DESC);

ALTER TABLE public.customer_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_tag_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_consent_events ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.customer_tags FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.customer_tag_assignments FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.customer_notes FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.customer_consent_events FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE public.customer_tags, public.customer_tag_assignments,
  public.customer_notes, public.customer_consent_events TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.customer_tags_id_seq TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.customer_notes_id_seq TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.customer_consent_events_id_seq TO service_role;

CREATE OR REPLACE FUNCTION public.customer_crm_tags()
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_uid uuid := (SELECT auth.uid());
BEGIN
  IF v_uid IS NULL OR NOT (SELECT public.is_app_admin()) THEN
    RAISE EXCEPTION 'forbidden' USING ERRCODE = '42501';
  END IF;

  RETURN coalesce((
    SELECT jsonb_agg(jsonb_build_object(
      'id', t.id,
      'name', t.name,
      'color', t.color,
      'customer_count', (
        SELECT count(*) FROM public.customer_tag_assignments a WHERE a.tag_id = t.id
      )
    ) ORDER BY lower(t.name))
    FROM public.customer_tags t
  ), '[]'::jsonb);
END;
$$;

CREATE OR REPLACE FUNCTION public.customer_crm_profile(p_customer_id integer)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_uid uuid := (SELECT auth.uid());
  v_result jsonb;
BEGIN
  IF v_uid IS NULL OR NOT (SELECT public.is_app_admin()) THEN
    RAISE EXCEPTION 'forbidden' USING ERRCODE = '42501';
  END IF;
  IF p_customer_id IS NULL OR NOT EXISTS (
    SELECT 1 FROM public.customers c WHERE c.id = p_customer_id
  ) THEN
    RAISE EXCEPTION 'customer_not_found' USING ERRCODE = 'P0002';
  END IF;

  WITH eligible_sales AS (
    SELECT s.id, s.sale_date, s.created_at, s.total, s.status, s.payment_method
    FROM public.sales s
    WHERE s.customer_id = p_customer_id
      AND coalesce(s.status, 'completed') <> 'pending_payment'
  ),
  returned AS (
    SELECT sr.sale_id, sum(sr.refund_total)::numeric AS refund_total
    FROM public.sale_returns sr
    JOIN eligible_sales es ON es.id = sr.sale_id
    GROUP BY sr.sale_id
  ),
  sale_facts AS (
    SELECT es.*,
      coalesce(r.refund_total, 0)::numeric AS refund_total,
      greatest(0, es.total - coalesce(r.refund_total, 0))::numeric AS net_total
    FROM eligible_sales es
    LEFT JOIN returned r ON r.sale_id = es.id
  ),
  metrics AS (
    SELECT
      count(*)::bigint AS sale_count,
      coalesce(sum(total), 0)::numeric AS gross_spent,
      coalesce(sum(refund_total), 0)::numeric AS refund_total,
      coalesce(sum(net_total), 0)::numeric AS net_spent,
      coalesce(avg(net_total), 0)::numeric AS average_ticket,
      min(sale_date) AS first_purchase_at,
      max(sale_date) AS last_purchase_at
    FROM sale_facts
  )
  SELECT jsonb_build_object(
    'customer', jsonb_build_object(
      'id', c.id,
      'first_name', c.first_name,
      'last_name', c.last_name,
      'email', c.email,
      'phone', c.phone,
      'created_at', c.created_at
    ),
    'metrics', jsonb_build_object(
      'sale_count', m.sale_count,
      'gross_spent', m.gross_spent,
      'refund_total', m.refund_total,
      'net_spent', m.net_spent,
      'average_ticket', round(m.average_ticket, 2),
      'first_purchase_at', m.first_purchase_at,
      'last_purchase_at', m.last_purchase_at
    ),
    'tags', coalesce((
      SELECT jsonb_agg(jsonb_build_object(
        'id', t.id, 'name', t.name, 'color', t.color
      ) ORDER BY lower(t.name))
      FROM public.customer_tag_assignments a
      JOIN public.customer_tags t ON t.id = a.tag_id
      WHERE a.customer_id = c.id
    ), '[]'::jsonb),
    'notes', coalesce((
      SELECT jsonb_agg(jsonb_build_object(
        'id', n.id,
        'body', n.body,
        'created_at', n.created_at
      ) ORDER BY n.created_at DESC, n.id DESC)
      FROM (
        SELECT * FROM public.customer_notes
        WHERE customer_id = c.id AND archived_at IS NULL
        ORDER BY created_at DESC, id DESC
        LIMIT 50
      ) n
    ), '[]'::jsonb),
    'consent', coalesce((
      SELECT jsonb_build_object(
        'granted', e.granted,
        'source', e.source,
        'evidence_note', e.evidence_note,
        'created_at', e.created_at
      )
      FROM public.customer_consent_events e
      WHERE e.customer_id = c.id AND e.channel = 'marketing'
      ORDER BY e.created_at DESC, e.id DESC
      LIMIT 1
    ), jsonb_build_object(
      'granted', false, 'source', null, 'evidence_note', null, 'created_at', null
    )),
    'consent_history', coalesce((
      SELECT jsonb_agg(jsonb_build_object(
        'id', e.id,
        'granted', e.granted,
        'source', e.source,
        'evidence_note', e.evidence_note,
        'created_at', e.created_at
      ) ORDER BY e.created_at DESC, e.id DESC)
      FROM (
        SELECT * FROM public.customer_consent_events
        WHERE customer_id = c.id AND channel = 'marketing'
        ORDER BY created_at DESC, id DESC
        LIMIT 20
      ) e
    ), '[]'::jsonb),
    'activity', coalesce((
      SELECT jsonb_agg(x.event ORDER BY x.event_at DESC)
      FROM (
        SELECT event, event_at
        FROM (
          SELECT jsonb_build_object(
            'id', 'sale-' || sf.id,
            'type', 'sale',
            'event_at', sf.sale_date,
            'sale_id', sf.id,
            'amount', sf.total,
            'status', sf.status,
            'payment_method', sf.payment_method
          ) AS event, sf.sale_date AS event_at
          FROM sale_facts sf
          UNION ALL
          SELECT jsonb_build_object(
            'id', 'return-' || sr.id,
            'type', 'return',
            'event_at', sr.created_at,
            'sale_id', sr.sale_id,
            'amount', -sr.refund_total,
            'credit_note_number', sr.credit_note_number,
            'reason', sr.reason
          ) AS event, sr.created_at AS event_at
          FROM public.sale_returns sr
          JOIN eligible_sales es ON es.id = sr.sale_id
        ) events
        ORDER BY event_at DESC
        LIMIT 50
      ) x
    ), '[]'::jsonb)
  ) INTO v_result
  FROM public.customers c
  CROSS JOIN metrics m
  WHERE c.id = p_customer_id;

  RETURN v_result;
END;
$$;

CREATE OR REPLACE FUNCTION public.customer_crm_upsert_tag(
  p_id bigint,
  p_name text,
  p_color text DEFAULT '#ec4899'
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_uid uuid := (SELECT auth.uid());
  v_tag public.customer_tags%ROWTYPE;
  v_name text := trim(coalesce(p_name, ''));
  v_color text := coalesce(nullif(trim(p_color), ''), '#ec4899');
BEGIN
  IF v_uid IS NULL OR NOT (SELECT public.is_app_admin()) THEN
    RAISE EXCEPTION 'forbidden' USING ERRCODE = '42501';
  END IF;
  IF char_length(v_name) NOT BETWEEN 2 AND 30 OR v_color !~ '^#[0-9A-Fa-f]{6}$' THEN
    RAISE EXCEPTION 'invalid_customer_tag' USING ERRCODE = '22023';
  END IF;

  IF p_id IS NULL THEN
    INSERT INTO public.customer_tags (name, color, created_by)
    VALUES (v_name, v_color, v_uid)
    RETURNING * INTO v_tag;
  ELSE
    UPDATE public.customer_tags
    SET name = v_name, color = v_color, updated_by = v_uid, updated_at = now()
    WHERE id = p_id
    RETURNING * INTO v_tag;
    IF NOT FOUND THEN
      RAISE EXCEPTION 'customer_tag_not_found' USING ERRCODE = 'P0002';
    END IF;
  END IF;

  RETURN jsonb_build_object('id', v_tag.id, 'name', v_tag.name, 'color', v_tag.color);
EXCEPTION
  WHEN unique_violation THEN
    RAISE EXCEPTION 'customer_tag_name_exists' USING ERRCODE = '23505';
END;
$$;

CREATE OR REPLACE FUNCTION public.customer_crm_set_tags(
  p_customer_id integer,
  p_tag_ids bigint[]
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_uid uuid := (SELECT auth.uid());
  v_ids bigint[] := coalesce(p_tag_ids, '{}'::bigint[]);
  v_distinct_count integer;
BEGIN
  IF v_uid IS NULL OR NOT (SELECT public.is_app_admin()) THEN
    RAISE EXCEPTION 'forbidden' USING ERRCODE = '42501';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.customers WHERE id = p_customer_id) THEN
    RAISE EXCEPTION 'customer_not_found' USING ERRCODE = 'P0002';
  END IF;

  SELECT count(*) INTO v_distinct_count
  FROM (SELECT DISTINCT unnest(v_ids) AS id) d;
  IF v_distinct_count > 10 OR v_distinct_count <> cardinality(v_ids) THEN
    RAISE EXCEPTION 'invalid_customer_tags' USING ERRCODE = '22023';
  END IF;
  IF EXISTS (
    SELECT 1 FROM unnest(v_ids) AS requested(id)
    WHERE NOT EXISTS (SELECT 1 FROM public.customer_tags t WHERE t.id = requested.id)
  ) THEN
    RAISE EXCEPTION 'customer_tag_not_found' USING ERRCODE = 'P0002';
  END IF;

  DELETE FROM public.customer_tag_assignments
  WHERE customer_id = p_customer_id AND NOT (tag_id = ANY(v_ids));

  INSERT INTO public.customer_tag_assignments (customer_id, tag_id, assigned_by)
  SELECT p_customer_id, id, v_uid FROM unnest(v_ids) AS requested(id)
  ON CONFLICT (customer_id, tag_id) DO NOTHING;

  RETURN jsonb_build_object('customer_id', p_customer_id, 'tag_ids', to_jsonb(v_ids));
END;
$$;

CREATE OR REPLACE FUNCTION public.customer_crm_add_note(
  p_customer_id integer,
  p_body text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_uid uuid := (SELECT auth.uid());
  v_body text := trim(coalesce(p_body, ''));
  v_note public.customer_notes%ROWTYPE;
BEGIN
  IF v_uid IS NULL OR NOT (SELECT public.is_app_admin()) THEN
    RAISE EXCEPTION 'forbidden' USING ERRCODE = '42501';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.customers WHERE id = p_customer_id) THEN
    RAISE EXCEPTION 'customer_not_found' USING ERRCODE = 'P0002';
  END IF;
  IF char_length(v_body) NOT BETWEEN 1 AND 1000 THEN
    RAISE EXCEPTION 'invalid_customer_note' USING ERRCODE = '22023';
  END IF;

  INSERT INTO public.customer_notes (customer_id, body, created_by)
  VALUES (p_customer_id, v_body, v_uid)
  RETURNING * INTO v_note;
  RETURN jsonb_build_object('id', v_note.id, 'body', v_note.body, 'created_at', v_note.created_at);
END;
$$;

CREATE OR REPLACE FUNCTION public.customer_crm_archive_note(p_note_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_uid uuid := (SELECT auth.uid());
  v_customer_id integer;
BEGIN
  IF v_uid IS NULL OR NOT (SELECT public.is_app_admin()) THEN
    RAISE EXCEPTION 'forbidden' USING ERRCODE = '42501';
  END IF;
  UPDATE public.customer_notes
  SET archived_at = now(), archived_by = v_uid
  WHERE id = p_note_id AND archived_at IS NULL
  RETURNING customer_id INTO v_customer_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'customer_note_not_found' USING ERRCODE = 'P0002';
  END IF;
  RETURN jsonb_build_object('id', p_note_id, 'customer_id', v_customer_id, 'archived', true);
END;
$$;

CREATE OR REPLACE FUNCTION public.customer_crm_record_consent(
  p_customer_id integer,
  p_granted boolean,
  p_source text,
  p_evidence_note text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_uid uuid := (SELECT auth.uid());
  v_source text := lower(trim(coalesce(p_source, '')));
  v_note text := nullif(trim(coalesce(p_evidence_note, '')), '');
  v_event public.customer_consent_events%ROWTYPE;
BEGIN
  IF v_uid IS NULL OR NOT (SELECT public.is_app_admin()) THEN
    RAISE EXCEPTION 'forbidden' USING ERRCODE = '42501';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.customers WHERE id = p_customer_id) THEN
    RAISE EXCEPTION 'customer_not_found' USING ERRCODE = 'P0002';
  END IF;
  IF p_granted IS NULL
    OR v_source NOT IN ('presencial', 'whatsapp', 'web', 'telefono', 'otro')
    OR (v_note IS NOT NULL AND char_length(v_note) > 500) THEN
    RAISE EXCEPTION 'invalid_customer_consent' USING ERRCODE = '22023';
  END IF;

  INSERT INTO public.customer_consent_events (
    customer_id, granted, source, evidence_note, recorded_by
  ) VALUES (p_customer_id, p_granted, v_source, v_note, v_uid)
  RETURNING * INTO v_event;

  RETURN jsonb_build_object(
    'id', v_event.id,
    'granted', v_event.granted,
    'source', v_event.source,
    'evidence_note', v_event.evidence_note,
    'created_at', v_event.created_at
  );
END;
$$;

REVOKE ALL ON FUNCTION public.customer_crm_tags() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.customer_crm_profile(integer) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.customer_crm_upsert_tag(bigint, text, text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.customer_crm_set_tags(integer, bigint[]) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.customer_crm_add_note(integer, text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.customer_crm_archive_note(bigint) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.customer_crm_record_consent(integer, boolean, text, text) FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION public.customer_crm_tags() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.customer_crm_profile(integer) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.customer_crm_upsert_tag(bigint, text, text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.customer_crm_set_tags(integer, bigint[]) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.customer_crm_add_note(integer, text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.customer_crm_archive_note(bigint) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.customer_crm_record_consent(integer, boolean, text, text) TO authenticated, service_role;

COMMENT ON TABLE public.customer_notes IS
  'Stage 6.5: notas CRM admin-only; archivar conserva evidencia y autor.';
COMMENT ON TABLE public.customer_consent_events IS
  'Stage 6.5: historial append-only del consentimiento de marketing.';
COMMENT ON FUNCTION public.customer_crm_profile(integer) IS
  'Stage 6.5: perfil CRM admin-only con métricas netas, actividad, etiquetas, notas y consentimiento.';
