-- =============================================================================
-- Stage 6.3 — Devoluciones y notas de crédito
-- =============================================================================
-- Forward-only. La venta original y sus líneas permanecen inmutables.

CREATE TABLE public.sale_item_components (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_item_id bigint NOT NULL REFERENCES public.sale_items(id) ON DELETE CASCADE,
  product_id bigint REFERENCES public.products(id) ON DELETE SET NULL,
  product_name text NOT NULL,
  quantity_per_unit integer NOT NULL CHECK (quantity_per_unit > 0),
  snapshot_source text NOT NULL
    CHECK (snapshot_source IN ('sale_time', 'legacy_product', 'legacy_current_combo')),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (sale_item_id, product_id)
);

CREATE INDEX sale_item_components_sale_item_idx
  ON public.sale_item_components (sale_item_id);
CREATE INDEX sale_item_components_product_idx
  ON public.sale_item_components (product_id);

CREATE TABLE public.sale_returns (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  credit_note_number bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  sale_id bigint NOT NULL REFERENCES public.sales(id) ON DELETE RESTRICT,
  status text NOT NULL DEFAULT 'completed' CHECK (status = 'completed'),
  reason text NOT NULL CHECK (char_length(trim(reason)) BETWEEN 3 AND 500),
  refund_method text NOT NULL CHECK (
    refund_method IN (
      'efectivo', 'transferencia', 'tarjeta', 'mercadopago',
      'credito_cancelado', 'otro'
    )
  ),
  refund_total numeric(12,2) NOT NULL CHECK (refund_total > 0),
  restock boolean NOT NULL DEFAULT true,
  idempotency_key uuid NOT NULL UNIQUE,
  created_by uuid NOT NULL REFERENCES auth.users(id),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX sale_returns_sale_created_idx
  ON public.sale_returns (sale_id, created_at DESC);
CREATE INDEX sale_returns_created_idx
  ON public.sale_returns (created_at DESC);
CREATE INDEX sale_returns_created_by_idx
  ON public.sale_returns (created_by);

CREATE TABLE public.sale_return_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  return_id uuid NOT NULL REFERENCES public.sale_returns(id) ON DELETE RESTRICT,
  sale_item_id bigint NOT NULL REFERENCES public.sale_items(id) ON DELETE RESTRICT,
  product_id bigint,
  product_name text NOT NULL,
  quantity integer NOT NULL CHECK (quantity > 0),
  unit_price numeric(12,2) NOT NULL CHECK (unit_price >= 0),
  refund_amount numeric(12,2) NOT NULL CHECK (refund_amount > 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (return_id, sale_item_id)
);

CREATE INDEX sale_return_items_return_idx
  ON public.sale_return_items (return_id);
CREATE INDEX sale_return_items_sale_item_idx
  ON public.sale_return_items (sale_item_id);
CREATE INDEX sale_return_items_product_idx
  ON public.sale_return_items (product_id);

CREATE TABLE public.sale_return_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  return_id uuid NOT NULL REFERENCES public.sale_returns(id) ON DELETE RESTRICT,
  event_type text NOT NULL CHECK (event_type IN ('created')),
  actor_user_id uuid NOT NULL REFERENCES auth.users(id),
  meta jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX sale_return_events_return_idx
  ON public.sale_return_events (return_id, created_at);
CREATE INDEX sale_return_events_actor_idx
  ON public.sale_return_events (actor_user_id);

ALTER TABLE public.sale_item_components ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sale_returns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sale_return_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sale_return_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY sale_returns_select_admin
  ON public.sale_returns FOR SELECT TO authenticated
  USING ((SELECT public.is_app_admin()));
CREATE POLICY sale_return_items_select_admin
  ON public.sale_return_items FOR SELECT TO authenticated
  USING ((SELECT public.is_app_admin()));
CREATE POLICY sale_return_events_select_admin
  ON public.sale_return_events FOR SELECT TO authenticated
  USING ((SELECT public.is_app_admin()));

REVOKE ALL ON TABLE public.sale_item_components FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.sale_returns FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.sale_return_items FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.sale_return_events FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public.sale_returns TO authenticated;
GRANT SELECT ON TABLE public.sale_return_items TO authenticated;
GRANT SELECT ON TABLE public.sale_return_events TO authenticated;
GRANT ALL ON TABLE public.sale_item_components, public.sale_returns,
  public.sale_return_items, public.sale_return_events TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.sale_item_components_id_seq TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.sale_returns_credit_note_number_seq TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.sale_return_items_id_seq TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.sale_return_events_id_seq TO service_role;

-- Snapshot autoritativo de componentes al insertar cada línea futura.
CREATE OR REPLACE FUNCTION public.snapshot_sale_item_components()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF NEW.product_id IS NOT NULL THEN
    INSERT INTO public.sale_item_components (
      sale_item_id, product_id, product_name, quantity_per_unit, snapshot_source
    )
    SELECT NEW.id, p.id, p.name, 1, 'sale_time'
    FROM public.products p
    WHERE p.id = NEW.product_id
    ON CONFLICT (sale_item_id, product_id) DO NOTHING;
  ELSIF NEW.combo_id IS NOT NULL THEN
    INSERT INTO public.sale_item_components (
      sale_item_id, product_id, product_name, quantity_per_unit, snapshot_source
    )
    SELECT NEW.id, p.id, p.name, ci.quantity, 'sale_time'
    FROM public.combo_items ci
    JOIN public.products p ON p.id = ci.product_id
    WHERE ci.combo_id = NEW.combo_id
    ON CONFLICT (sale_item_id, product_id) DO NOTHING;
  END IF;
  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.snapshot_sale_item_components() FROM PUBLIC, anon, authenticated;

CREATE TRIGGER sale_items_snapshot_components
AFTER INSERT ON public.sale_items
FOR EACH ROW EXECUTE FUNCTION public.snapshot_sale_item_components();

-- Backfill: producto directo es exacto. Combo legacy usa su composición vigente
-- y queda marcado para que la procedencia sea auditable.
INSERT INTO public.sale_item_components (
  sale_item_id, product_id, product_name, quantity_per_unit, snapshot_source
)
SELECT si.id, p.id, p.name, 1, 'legacy_product'
FROM public.sale_items si
JOIN public.products p ON p.id = si.product_id
WHERE si.product_id IS NOT NULL
ON CONFLICT (sale_item_id, product_id) DO NOTHING;

INSERT INTO public.sale_item_components (
  sale_item_id, product_id, product_name, quantity_per_unit, snapshot_source
)
SELECT si.id, p.id, p.name, ci.quantity, 'legacy_current_combo'
FROM public.sale_items si
JOIN public.combo_items ci ON ci.combo_id = si.combo_id
JOIN public.products p ON p.id = ci.product_id
WHERE si.product_id IS NULL AND si.combo_id IS NOT NULL
ON CONFLICT (sale_item_id, product_id) DO NOTHING;

CREATE OR REPLACE FUNCTION public.create_sale_return(p_payload jsonb)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_uid uuid := (SELECT auth.uid());
  v_sale_id bigint;
  v_reason text;
  v_refund_method text;
  v_restock boolean;
  v_idempotency_key uuid;
  v_lines jsonb;
  v_sale public.sales%ROWTYPE;
  v_return_id uuid;
  v_credit_note_number bigint;
  v_refund_total numeric(12,2) := 0;
  v_existing jsonb;
  v_line record;
  v_prior_qty integer;
  v_prior_amount numeric(12,2);
  v_available integer;
  v_amount numeric(12,2);
BEGIN
  IF v_uid IS NULL OR NOT public.is_app_admin() THEN
    RAISE EXCEPTION 'forbidden' USING ERRCODE = '42501';
  END IF;
  IF p_payload IS NULL OR jsonb_typeof(p_payload) <> 'object' THEN
    RAISE EXCEPTION 'invalid_payload' USING ERRCODE = '22023';
  END IF;

  BEGIN
    v_sale_id := (p_payload->>'sale_id')::bigint;
    v_idempotency_key := (p_payload->>'idempotency_key')::uuid;
  EXCEPTION WHEN OTHERS THEN
    RAISE EXCEPTION 'invalid_identifiers' USING ERRCODE = '22023';
  END;
  v_reason := trim(coalesce(p_payload->>'reason', ''));
  v_refund_method := trim(coalesce(p_payload->>'refund_method', ''));
  v_restock := coalesce((p_payload->>'restock')::boolean, true);
  v_lines := p_payload->'lines';

  IF char_length(v_reason) < 3 OR char_length(v_reason) > 500 THEN
    RAISE EXCEPTION 'invalid_reason' USING ERRCODE = '22023';
  END IF;
  IF v_refund_method NOT IN (
    'efectivo', 'transferencia', 'tarjeta', 'mercadopago',
    'credito_cancelado', 'otro'
  ) THEN
    RAISE EXCEPTION 'invalid_refund_method' USING ERRCODE = '22023';
  END IF;
  IF v_lines IS NULL OR jsonb_typeof(v_lines) <> 'array'
     OR jsonb_array_length(v_lines) = 0 THEN
    RAISE EXCEPTION 'return_lines_required' USING ERRCODE = '22023';
  END IF;

  SELECT jsonb_build_object(
    'id', r.id,
    'credit_note_number', r.credit_note_number,
    'sale_id', r.sale_id,
    'refund_total', r.refund_total,
    'restock', r.restock,
    'idempotent_replay', true
  )
  INTO v_existing
  FROM public.sale_returns r
  WHERE r.idempotency_key = v_idempotency_key;
  IF v_existing IS NOT NULL THEN RETURN v_existing; END IF;

  PERFORM pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('stage63:sale-return:' || v_sale_id::text, 0)
  );

  SELECT * INTO v_sale FROM public.sales s WHERE s.id = v_sale_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'sale_not_found' USING ERRCODE = 'P0002';
  END IF;
  IF v_sale.status NOT IN ('completed', 'pending_payment') THEN
    RAISE EXCEPTION 'sale_not_returnable' USING ERRCODE = '23514';
  END IF;
  IF v_sale.status = 'pending_payment' AND v_refund_method <> 'credito_cancelado' THEN
    RAISE EXCEPTION 'pending_sale_requires_credit_cancellation' USING ERRCODE = '23514';
  END IF;
  IF v_sale.status = 'completed' AND v_refund_method = 'credito_cancelado' THEN
    RAISE EXCEPTION 'completed_sale_requires_refund_method' USING ERRCODE = '23514';
  END IF;

  IF EXISTS (
    SELECT 1 FROM jsonb_array_elements(v_lines) x(elem)
    GROUP BY elem->>'sale_item_id' HAVING count(*) > 1
  ) THEN
    RAISE EXCEPTION 'duplicate_return_line' USING ERRCODE = '23514';
  END IF;

  CREATE TEMP TABLE _stage63_lines (
    sale_item_id bigint PRIMARY KEY,
    product_id bigint,
    product_name text,
    quantity integer,
    unit_price numeric(12,2),
    refund_amount numeric(12,2)
  ) ON COMMIT DROP;

  FOR v_line IN
    SELECT
      si.id,
      si.product_id::bigint AS product_id,
      si.product_name,
      si.quantity,
      si.unit_price::numeric(12,2) AS unit_price,
      si.subtotal::numeric(12,2) AS subtotal,
      (x.elem->>'quantity')::integer AS requested_qty
    FROM jsonb_array_elements(v_lines) x(elem)
    JOIN public.sale_items si
      ON si.id = (x.elem->>'sale_item_id')::bigint
     AND si.sale_id = v_sale_id
    ORDER BY si.id
    FOR UPDATE OF si
  LOOP
    IF v_line.requested_qty IS NULL OR v_line.requested_qty <= 0 THEN
      RAISE EXCEPTION 'invalid_return_quantity' USING ERRCODE = '22023';
    END IF;
    SELECT coalesce(sum(ri.quantity),0), coalesce(sum(ri.refund_amount),0)
      INTO v_prior_qty, v_prior_amount
    FROM public.sale_return_items ri
    JOIN public.sale_returns r ON r.id = ri.return_id
    WHERE ri.sale_item_id = v_line.id AND r.status = 'completed';

    v_available := v_line.quantity - v_prior_qty;
    IF v_line.requested_qty > v_available THEN
      RAISE EXCEPTION 'return_quantity_exceeds_available' USING ERRCODE = '23514';
    END IF;
    IF v_line.requested_qty = v_available THEN
      v_amount := v_line.subtotal - v_prior_amount;
    ELSE
      v_amount := round(v_line.subtotal * v_line.requested_qty / v_line.quantity, 2);
    END IF;
    IF v_amount <= 0 THEN
      RAISE EXCEPTION 'invalid_refund_amount' USING ERRCODE = '23514';
    END IF;
    INSERT INTO _stage63_lines VALUES (
      v_line.id, v_line.product_id, v_line.product_name,
      v_line.requested_qty, v_line.unit_price, v_amount
    );
    v_refund_total := v_refund_total + v_amount;
  END LOOP;

  IF (SELECT count(*) FROM _stage63_lines) <> jsonb_array_length(v_lines) THEN
    RAISE EXCEPTION 'sale_item_not_found' USING ERRCODE = 'P0002';
  END IF;
  IF v_refund_total <= 0 OR v_refund_total > v_sale.total THEN
    RAISE EXCEPTION 'invalid_refund_total' USING ERRCODE = '23514';
  END IF;

  INSERT INTO public.sale_returns (
    sale_id, reason, refund_method, refund_total, restock,
    idempotency_key, created_by
  ) VALUES (
    v_sale_id, v_reason, v_refund_method, v_refund_total, v_restock,
    v_idempotency_key, v_uid
  ) RETURNING id, credit_note_number INTO v_return_id, v_credit_note_number;

  INSERT INTO public.sale_return_items (
    return_id, sale_item_id, product_id, product_name,
    quantity, unit_price, refund_amount
  )
  SELECT v_return_id, sale_item_id, product_id, product_name,
    quantity, unit_price, refund_amount
  FROM _stage63_lines;

  IF v_restock THEN
    IF EXISTS (
      SELECT 1
      FROM _stage63_lines l
      LEFT JOIN public.sale_item_components c ON c.sale_item_id = l.sale_item_id
      GROUP BY l.sale_item_id
      HAVING count(c.id) = 0
    ) THEN
      RAISE EXCEPTION 'missing_component_snapshot' USING ERRCODE = '23514';
    END IF;

    WITH restored AS (
      SELECT c.product_id, sum(c.quantity_per_unit * l.quantity)::integer AS qty
      FROM _stage63_lines l
      JOIN public.sale_item_components c ON c.sale_item_id = l.sale_item_id
      WHERE c.product_id IS NOT NULL
      GROUP BY c.product_id
    )
    UPDATE public.products p
    SET stock = p.stock + restored.qty
    FROM restored WHERE p.id = restored.product_id;

    INSERT INTO public.stock_movements (
      product_id, type, quantity, reference_type, reference_id, notes, user_id
    )
    SELECT c.product_id, 'adjustment',
      sum(c.quantity_per_unit * l.quantity)::integer,
      'sale_return', v_credit_note_number,
      'Devolución NC-' || lpad(v_credit_note_number::text, 6, '0'),
      v_uid
    FROM _stage63_lines l
    JOIN public.sale_item_components c ON c.sale_item_id = l.sale_item_id
    WHERE c.product_id IS NOT NULL
    GROUP BY c.product_id;
  END IF;

  INSERT INTO public.sale_return_events (
    return_id, event_type, actor_user_id, meta
  ) VALUES (
    v_return_id, 'created', v_uid,
    jsonb_build_object(
      'sale_id', v_sale_id,
      'refund_total', v_refund_total,
      'refund_method', v_refund_method,
      'restock', v_restock,
      'line_count', (SELECT count(*) FROM _stage63_lines)
    )
  );

  RETURN jsonb_build_object(
    'id', v_return_id,
    'credit_note_number', v_credit_note_number,
    'sale_id', v_sale_id,
    'refund_total', v_refund_total,
    'restock', v_restock,
    'idempotent_replay', false
  );
EXCEPTION
  WHEN unique_violation THEN
    SELECT jsonb_build_object(
      'id', r.id,
      'credit_note_number', r.credit_note_number,
      'sale_id', r.sale_id,
      'refund_total', r.refund_total,
      'restock', r.restock,
      'idempotent_replay', true
    ) INTO v_existing
    FROM public.sale_returns r WHERE r.idempotency_key = v_idempotency_key;
    IF v_existing IS NOT NULL THEN RETURN v_existing; END IF;
    RAISE;
END;
$$;

REVOKE ALL ON FUNCTION public.create_sale_return(jsonb) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.create_sale_return(jsonb) TO authenticated, service_role;

-- Impide que el RPC legacy de borrado restaure stock por segunda vez.
CREATE OR REPLACE FUNCTION public.prevent_delete_sale_with_returns()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF EXISTS (SELECT 1 FROM public.sale_returns r WHERE r.sale_id = OLD.id) THEN
    RAISE EXCEPTION 'sale_has_returns' USING ERRCODE = '23514';
  END IF;
  RETURN OLD;
END;
$$;
REVOKE ALL ON FUNCTION public.prevent_delete_sale_with_returns() FROM PUBLIC, anon, authenticated;

CREATE TRIGGER sales_prevent_delete_with_returns
BEFORE DELETE ON public.sales
FOR EACH ROW EXECUTE FUNCTION public.prevent_delete_sale_with_returns();

CREATE OR REPLACE FUNCTION public.prevent_delete_returned_sale_item()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM public.sale_return_items ri WHERE ri.sale_item_id = OLD.id
  ) THEN
    RAISE EXCEPTION 'sale_has_returns' USING ERRCODE = '23514';
  END IF;
  RETURN OLD;
END;
$$;
REVOKE ALL ON FUNCTION public.prevent_delete_returned_sale_item()
  FROM PUBLIC, anon, authenticated;

CREATE TRIGGER sale_items_prevent_delete_when_returned
BEFORE DELETE ON public.sale_items
FOR EACH ROW EXECUTE FUNCTION public.prevent_delete_returned_sale_item();

COMMENT ON FUNCTION public.create_sale_return(jsonb) IS
  'Stage 6.3: nota de crédito atómica, monto autoritativo, límite acumulado y stock por snapshot.';
